DROP TABLE assign;
DROP TABLE bill;
DROP TABLE customer;
DROP TABLE employee;
DROP TABLE empskill;
DROP TABLE project;
DROP TABLE region;
DROP TABLE skill;
DROP TABLE task;
DROP TABLE ts;
DROP TABLE worklog;

CREATE TABLE assign (
  ASSIGN_ID number(10) NOT NULL AUTO_INCREMENT,
  EMP_ID number(10) NOT NULL,
  TASK_ID number(10) NOT NULL,
  ASSIGN_BEGINDATE date NOT NULL,
  ASSIGN_ENDDATE date NOT NULL
) ;

CREATE TABLE bill (
  BILL_ID number(10) NOT NULL AUTO_INCREMENT,
  PROJ_ID number(10) NOT NULL,
  BILL_DATE date NOT NULL
) ;

CREATE TABLE customer (
  CUST_ID number(10) NOT NULL AUTO_INCREMENT,
  REG_ID number(10) NOT NULL,
  CUST_NAME varchar2(255) NOT NULL,
  CUST_PHONE number(10) NOT NULL
) ;

CREATE TABLE employee (
  EMP_ID number(10) NOT NULL AUTO_INCREMENT,
  REG_ID number(10) NOT NULL,
  EMP_LNAME varchar2(255) NOT NULL,
  EMP_MNAME varchar2(255) NOT NULL,
  EMP_FNAME varchar2(255) NOT NULL,
  EMP_HIREDATE date NOT NULL
) ;

CREATE TABLE empskill (
  EMP_ID number(10) NOT NULL,
  SKILL_ID number(10) NOT NULL
) ;

CREATE TABLE project (
  PROJ_ID number(10) NOT NULL AUTO_INCREMENT,
  CUST_ID number(10) NOT NULL,
  EMP_ID number(10) NOT NULL,
  PROJ_DATE date NOT NULL,
  PROJ_DESCRIPT varchar2(1000) NOT NULL,
  PROJ_ESDATESTART date NOT NULL,
  PROJ_ESDATEEND date NOT NULL,
  PROJ_ESBUDGET number(10) NOT NULL,
  PROJ_ACDATESTART date NOT NULL,
  PROJ_ACDATEENDS date NOT NULL,
  PROJ_ACCOST number(10) NOT NULL
) ;

CREATE TABLE region (
  REG_ID number(10) NOT NULL AUTO_INCREMENT,
  REG_NAME varchar2(255) NOT NULL
) ;

CREATE TABLE skill (
  SKILL_ID number(10) NOT NULL AUTO_INCREMENT,
  SKILL_DESCRIPT varchar2(255) NOT NULL,
  SKILL_RATE number(10) NOT NULL
) ;

CREATE TABLE task (
  TASK_ID number(10) NOT NULL AUTO_INCREMENT,
  PROJ_ID number(10) NOT NULL,
  TASK_DESCRIPT varchar2(1000) NOT NULL,
  TASK_BEGINDATE date NOT NULL,
  TASK_ENDDATE date NOT NULL
) ;

CREATE TABLE ts (
  TS_ID number(10) NOT NULL AUTO_INCREMENT,
  TASK_ID number(10) NOT NULL,
  SKILL_ID number(10) NOT NULL,
  TS_QTY number(10) NOT NULL
) ;

CREATE TABLE worklog (
  WL_ID number(10) NOT NULL AUTO_INCREMENT,
  ASSIGN_ID number(10) NOT NULL,
  BILL_ID number(10) NOT NULL,
  WL_DATE date NOT NULL,
  WL_HOURS number(10) NOT NULL
) ;

ALTER TABLE assign
  ADD PRIMARY KEY (ASSIGN_ID),
  ADD CONSTRAINT EMP_ID FK FOREIGN KEY (EMP_ID) REFERENCES employee (EMP_ID),
  ADD CONSTRAINT TASK_ID FK FOREIGN KEY (TASK_ID) REFERENCES ts (TASK_ID);

ALTER TABLE bill
  ADD PRIMARY KEY (BILL_ID),
  ADD CONSTRAINT PROJ_ID FOREIGN KEY (PROJ_ID) REFERENCES project (PROJ_ID);

ALTER TABLE customer
  ADD PRIMARY KEY (CUST_ID),
  ADD CONSTRAINT REG_ID FK FOREIGN KEY (REG_ID) REFERENCES region (REG_ID);


ALTER TABLE employee
  ADD PRIMARY KEY (EMP_ID),
  ADD CONSTRAINT employee_ibfk_1 FOREIGN KEY (REG_ID) REFERENCES region (REG_ID);

ALTER TABLE empskill
  ADD PRIMARY KEY (EMP_ID,SKILL_ID),
  ADD CONSTRAINT empskill_ibfk_2 FOREIGN KEY (SKILL_ID) REFERENCES skill (SKILL_ID),
  ADD CONSTRAINT empskill_ibfk_3 FOREIGN KEY (EMP_ID) REFERENCES employee (EMP_ID);

ALTER TABLE project
  ADD PRIMARY KEY (PROJ_ID),
  ADD CONSTRAINT project_ibfk_1 FOREIGN KEY (CUST_ID) REFERENCES customer (CUST_ID),
  ADD CONSTRAINT project_ibfk_2 FOREIGN KEY (EMP_ID) REFERENCES employee (EMP_ID);


ALTER TABLE region
  ADD PRIMARY KEY (REG_ID);


ALTER TABLE skill
  ADD PRIMARY KEY (SKILL_ID);


ALTER TABLE task
  ADD PRIMARY KEY (TASK_ID),
  ADD CONSTRAINT task_ibfk_1 FOREIGN KEY (PROJ_ID) REFERENCES project (PROJ_ID);


ALTER TABLE ts
  ADD PRIMARY KEY (TASK_ID),
  ADD PRIMARY KEY (SKILL_ID),
  ADD CONSTRAINT ts_ibfk_1 FOREIGN KEY (TASK_ID) REFERENCES task (TASK_ID),
  ADD CONSTRAINT ts_ibfk_2 FOREIGN KEY (SKILL_ID) REFERENCES skill (SKILL_ID);

ALTER TABLE worklog
  ADD PRIMARY KEY (WL_ID),
  ADD CONSTRAINT worklog_ibfk_1 FOREIGN KEY (ASSIGN_ID) REFERENCES assign (ASSIGN_ID),
  ADD CONSTRAINT worklog_ibfk_2 FOREIGN KEY (BILL_ID) REFERENCES bill (BILL_ID);

