DROP TABLE assign;
DROP TABLE bill;
DROP TABLE customer;
DROP TABLE employee;
DROP TABLE empskill;
DROP TABLE project;
DROP TABLE region;
DROP TABLE skill;
DROP TABLE task;
DROP TABLE ts;
DROP TABLE worklog;

CREATE TABLE assign (
  ASSIGN_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  EMP_ID number(10) NOT NULL,
  TASK_ID number(10) NOT NULL,
  ASSIGN_BEGINDATE date NOT NULL,
  ASSIGN_ENDDATE date NOT NULL,
CONSTRAINT UNIQ_ASSIGN UNIQUE (TASK_ID)
) ;

CREATE TABLE bill (
  BILL_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  PROJ_ID number(10) NOT NULL,
  BILL_DATE date NOT NULL
) ;

CREATE TABLE customer (
  CUST_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  REG_ID number(10) NOT NULL,
  CUST_NAME varchar2(255) NOT NULL,
  CUST_PHONE number(10) NOT NULL
) ;

CREATE TABLE employee (
  EMP_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  REG_ID number(10) NOT NULL,
  EMP_LNAME varchar2(255) NOT NULL,
  EMP_MNAME varchar2(255) NOT NULL,
  EMP_FNAME varchar2(255) NOT NULL,
  EMP_HIREDATE date NOT NULL
) ;

CREATE TABLE empskill (
  EMP_ID number(10) NOT NULL,
  SKILL_ID number(10) NOT NULL
) ;

CREATE TABLE project (
  PROJ_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CUST_ID number(10) NOT NULL,
  EMP_ID number(10) NOT NULL,
  PROJ_DATE date NOT NULL,
  PROJ_DESCRIPT varchar2(1000) NOT NULL,
  PROJ_ESDATESTART date NOT NULL,
  PROJ_ESDATEEND date NOT NULL,
  PROJ_ESBUDGET number(10) NOT NULL,
  PROJ_ACDATESTART date NOT NULL,
  PROJ_ACDATEENDS date NOT NULL,
  PROJ_ACCOST number(10) NOT NULL
) ;

CREATE TABLE region (
  REG_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  REG_NAME varchar2(255) NOT NULL
) ;

CREATE TABLE skill (
  SKILL_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  SKILL_DESCRIPT varchar2(255) NOT NULL,
  SKILL_RATE number(10) NOT NULL
) ;

CREATE TABLE task (
  TASK_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  PROJ_ID number(10) NOT NULL,
  TASK_DESCRIPT varchar2(1000) NOT NULL,
  TASK_BEGINDATE date NOT NULL,
  TASK_ENDDATE date NOT NULL
) ;

CREATE TABLE ts (
  TS_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  TASK_ID number(10) NOT NULL,
  SKILL_ID number(10) NOT NULL,
  TS_QTY number(10) NOT NULL,
CONSTRAINT UNIQ_TS UNIQUE (TASK_ID)
) ;

CREATE TABLE worklog (
  WL_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ASSIGN_ID number(10) NOT NULL,
  BILL_ID number(10) NOT NULL,
  WL_DATE date NOT NULL,
  WL_HOURS number(10) NOT NULL
) ;


ALTER TABLE assign
ADD CONSTRAINT EMP_ID_FK FOREIGN KEY (EMP_ID) REFERENCES employee (EMP_ID);
ALTER TABLE assign
  ADD CONSTRAINT TASK_ID_FK FOREIGN KEY (TASK_ID) REFERENCES ts (TASK_ID);


ALTER TABLE bill
  ADD CONSTRAINT PROJ_ID_FK_BILL FOREIGN KEY (PROJ_ID) REFERENCES project (PROJ_ID);


ALTER TABLE customer
  ADD CONSTRAINT REG_ID_FK FOREIGN KEY (REG_ID) REFERENCES region (REG_ID);


ALTER TABLE employee
  ADD CONSTRAINT employee_ibfk_1 FOREIGN KEY (REG_ID) REFERENCES region (REG_ID);


ALTER TABLE empskill
  ADD CONSTRAINT empskill_ibfk_2 FOREIGN KEY (SKILL_ID) REFERENCES skill (SKILL_ID);
ALTER TABLE empskill
  ADD CONSTRAINT empskill_ibfk_3 FOREIGN KEY (EMP_ID) REFERENCES employee (EMP_ID);


ALTER TABLE project
  ADD CONSTRAINT project_ibfk_1 FOREIGN KEY (CUST_ID) REFERENCES customer (CUST_ID);
ALTER TABLE project
  ADD CONSTRAINT project_ibfk_2 FOREIGN KEY (EMP_ID) REFERENCES employee (EMP_ID);


ALTER TABLE task
  ADD CONSTRAINT task_ibfk_1 FOREIGN KEY (PROJ_ID) REFERENCES project (PROJ_ID);


ALTER TABLE ts
  ADD CONSTRAINT ts_ibfk_1 FOREIGN KEY (TASK_ID) REFERENCES task (TASK_ID);
ALTER TABLE ts
  ADD CONSTRAINT ts_ibfk_2 FOREIGN KEY (SKILL_ID) REFERENCES skill (SKILL_ID);

ALTER TABLE worklog
  ADD CONSTRAINT worklog_ibfk_1 FOREIGN KEY (ASSIGN_ID) REFERENCES assign (ASSIGN_ID);
ALTER TABLE worklog
  ADD CONSTRAINT worklog_ibfk_2 FOREIGN KEY (BILL_ID) REFERENCES bill (BILL_ID);