CREATE OR REPLACE PROCEDURE INSERT_WORKLOG (
    P_BILL_ID IN NUMBER,
    P_ASSIGN_ID IN NUMBER,
    P_HOURS IN NUMBER,
    P_WL_DATE IN DATE DEFAULT SYSDATE,
    P_WL_ID OUT NUMBER
)
AS
BEGIN
    INSERT INTO WORKLOG (BILL_ID, ASSIGN_ID, WL_HOURS, WL_DATE)
    VALUES (P_BILL_ID, P_ASSIGN_ID, P_HOURS, P_WL_DATE)
    RETURNING WL_ID INTO P_WL_ID;
    
    DBMS_OUTPUT.PUT_LINE('Worklog entry ' || P_WL_ID || ' inserted.');
    
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('An error occurred while inserting the worklog entry.');
END;
/
