CREATE OR REPLACE PROCEDURE INSERT_EMPLOYEE (
    P_EMP_ID IN NUMBER,
    P_REG_ID IN NUMBER,
    P_EMP_LNAME IN VARCHAR2,
    P_EMP_MNAME IN VARCHAR2,
    P_EMP_FNAME IN VARCHAR2,
    P_EMP_HIREDATE IN DATE
)
AS
BEGIN
    INSERT INTO EMPLOYEE (EMP_ID, REG_ID, EMP_LNAME, EMP_MNAME, EMP_FNAME, EMP_HIREDATE)
    VALUES (P_EMP_ID, P_REG_ID, P_EMP_LNAME, P_EMP_MNAME, P_EMP_FNAME, P_EMP_HIREDATE);
    
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Employee' || P_EMP_ID || 'inserted successfully.');
    
EXCEPTION
    WHEN OTHERS THEN ROLLBACK;
	DBMS_OUTPUT.PUT_LINE('Error inserting employee');
END;
/
