CREATE SEQUENCE INCREMENT_VAL START WITH 1 INCREMENT BY 1 NOCACHE;

CREATE OR REPLACE PROCEDURE INSERT_EMPLOYEE (
    P_REG_ID IN NUMBER,
    P_EMP_LNAME IN VARCHAR2,
    P_EMP_MNAME IN VARCHAR2,
    P_EMP_FNAME IN VARCHAR2,
    P_EMP_HIREDATE IN DATE,
    P_EMP_ID OUT NUMBER
)
AS
BEGIN
    INSERT INTO EMPLOYEE (EMP_ID, REG_ID, EMP_LNAME, EMP_MNAME, EMP_FNAME, EMP_HIREDATE)
    VALUES (INCREMENT_VAL.NEXTVAL, P_REG_ID, P_EMP_LNAME, P_EMP_MNAME, P_EMP_FNAME, P_EMP_HIREDATE);
    
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Employee inserted successfully.');
    
EXCEPTION
    WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE('Error inserting employee');
END;
/
