CREATE OR REPLACE PROCEDURE INSERT_WORKLOG (
    P_BILL_ID IN NUMBER,
    P_ASSIGN_ID IN NUMBER,
    P_HOURS IN NUMBER,
    P_WL_DATE IN DATE DEFAULT SYSDATE,
    P_WL_ID OUT NUMBER
)
AS
BEGIN
    SELECT INCREMENT_VAL.NEXTVAL INTO P_WL_ID FROM DUAL;
    
    INSERT INTO WORKLOG (WL_ID, BILL_ID, ASSIGN_ID, WL_HOURS, WL_DATE)
    VALUES (P_WL_ID, P_BILL_ID, P_ASSIGN_ID, P_HOURS, P_WL_DATE);
    
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Worklog entry ' || P_WL_ID || ' inserted.');
    
EXCEPTION
    WHEN OTHERS THEN ROLLBACK;
    DBMS_OUTPUT.PUT_LINE('Error inserting worklog entry.');
    
END;
/
