--TRIGGER

CREATE OR REPLACE TRIGGER UPDATE_ACCOST
AFTER INSERT OR UPDATE OF WL_HOURS ON WORKLOG
FOR EACH ROW
DECLARE
  V_SKILL_RATE NUMBER;
BEGIN
  IF TO_CHAR(SYSDATE, 'DY') = 'FRI' THEN
    SELECT S.SKILL_RATE INTO V_SKILL_RATE 
    FROM SKILL S
    JOIN TS ON S.SKILL_ID = TS.SKILL_ID 
    JOIN ASSIGN A ON TS.TS_ID = A.TS_ID 
    WHERE A.ASSIGN_ID = :NEW.ASSIGN_ID;

    UPDATE (
        SELECT P.PROJ_ACCOST 
        FROM PROJECT P
        JOIN BILL B ON P.PROJ_ID = B.PROJ_ID
        WHERE B.BILL_ID = :NEW.BILL_ID
    ) 
    SET PROJ_ACCOST = PROJ_ACCOST + (V_SKILL_RATE * :NEW.WL_HOURS);
  END IF;
END;
/ 
