/* VIEW FOR EMPLOYEE PAY */

CREATE VIEW EMPLOYEE_PAY AS
SELECT WORKLOG.EMP_ID, EMP_LNAME, WORKLOG.WL_ID, WORKLOG.ASN_ID,(WORKLOG.WL_HOURS*SKILL_RATE) AS "PAY"
FROM ASSIGN, WORKLOG, SKILL, TS, EMPLOYEE
WHERE ASSIGN.TS_ID = TS.TS_ID
	AND SKILL.SKILL_ID = TS.SKILL_ID
	AND WORKLOG.ASN_ID = ASSIGN.ASN_ID
        AND EMPLOYEE.EMP_ID = ASSIGN.EMP_ID;
