/* VIEW FOR UNFINISHED PROJECTS */

CREATE VIEW UNFINISHED_PROJECT AS
SELECT PRJ_ID, PRJ_DESCRIPTION, PRJ_ACDATESTART AS "DATE STARTED"
FROM PROJECT
WHERE PRJ_ACDATEENDS IS NULL;

/* VIEW FOR WORKLOGS WITHOUT BILLS */

CREATE VIEW UNBILLED_WORKLOGS AS
SELECT WL_ID, ASN_ID, WL_DATE, WL_HOURS
FROM WORKLOG
WHERE BILL_ID IS NULL;
